services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - backend-network

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  mongo-data:
